### ISSUE TITLE
Melon Port

### ISSUE THREAD

**Issue by MysticAx0lotl** [cgytrus/ThreeDashCustomMusic#3]
There's a new modloader API that's compatible with both 3Dash and 3Dash Plus called Melon. Afaik it can do as much as if not more than BepInEX. Mods written for BepInEX seem to be relatively easy to port to Melon, [3Dash Utils](https://github.com/art0007i/3dashutils) for example has a version for both loaders. SixDash as a dependency would need to be removed, hopefully that wouldn't be too big a hassle. A Melon port would be necessary to make this mod compatible with 3Dash Plus, as SixDash is not and never will be compatible with Plus.

**Comment by cgytrus** [comment]
6dash was meant as an api and an optimization mod, 6dash specifically was meant to be dependent on, and i am not interested in working on anything 3dash anyway. also, melon is designed for il2cpp.
if you feel the absolute need to have support, make a fork, or contact me on discord (`@cgytrus`) and we can discuss transferring ownership to you
